### ISSUE TITLE
LED 7 continuous not pulsing

### ISSUE THREAD

**Issue by 1986Mrk** [TomWhitwell/Turing-Pulse-Expander#2]
Dear Tom, dear Github,

Yesterday I built the Pulse Expander. When I connected the module to the Turing Machine all seemed fine, until the 7th LED started flickering dimly. After 15 seconds the LED was burning bright, no flickering anymore. 
My knowledge of circuits is close to nothing.. Could a component be burned? Do you have an idea which component it might be?
Some LEDs burn a bit brighter than others; is this normal?

**Comment by TomWhitwell** [comment]
Hi @1986Mrk that sounds like something is wrong. The LEDs all have the same power and the same resistors, so they should be (at least to the human eye) the same brightness. 
Start by double - checking your soldering, there could be a short circuit somewhere. If you can, post high-res images of the front and back of the board here.

**Comment by 1986Mrk** [comment]
Thanks for your reply Tom. I will check this later today and will post images of the front and back of the board.

Is the problem of a short circuit likely around the 7th LED or can this be anywhere?

**Comment by 1986Mrk** [comment]
Goodmorning Tom,

Yesterday I re-soldered the 2K resistor for the 7th LED and I measured the resistors with a multi meter; one 2K resistor gave 0,8K instead (brighter LED). Some others started around 1,5K and slowly went up in resistance; re-soldered those and all is fine now! Thanks for the design of these modules, gonna use them a lot!

**Comment by TomWhitwell** [comment]
That’s good to hear - enjoy!
