### ISSUE TITLE
Pulse MKII - "4+7" LED always on + step not sending trig

### ISSUE THREAD

**Issue by Suuupedepoissooon** [TomWhitwell/Turing-Pulse-Expander#6]
Hello everybody !

I am experiencing the same issue as mentionned by Madsiboy (closed), but with the "4+7" LED -> the LED is always on and no pulse is getting out of the step.
I tryed the other output of the turing machine and there is no difference, so the problem seems to be with the expender.
I double checked the chip but it seems I don't have the same issue as Madsiboy. I also replaced the two resistances related to the step but nothing changed.

Any idea ? Best regards

**Comment by TomWhitwell** [comment]
A few things you could try: 
- Post clear photos of back and front of the boards so we can have a look 
- Try removing the chip to see if anything changes - is led 7 still lit

**Comment by Suuupedepoissooon** [comment]
Hi Tom, you probably never received my previous answers because I send you several emails (spam folder ?).

Here is my latest answer : 
I removed the chip as you asked and no the led 7 does not lit anymore.
What do you suggest ?

Thx Tom

**Comment by TomWhitwell** [comment]
So - can't remember, have you replaced the 4081 already?

**Comment by Suuupedepoissooon** [comment]
No, I didn't have any new 4081 to replace it. But anyway, it seems that I accidentally damaged a stip on the PCB when I removed the old one...
